#cloud-config

coreos:
  etcd2:
    name: ampelos-01
    initial-advertise-peer-urls: http://$private_ipv4:2380
    listen-peer-urls: http://$private_ipv4:2380
    listen-client-urls: http://$private_ipv4:2379,http://127.0.0.1:2379
    advertise-client-urls: http://$private_ipv4:2379
    initial-cluster-token: ampelos-cluster-01
    initial-cluster: ampelos-01=http://10.1.0.51:2380,ampelos-02=http://10.1.0.52:2380,ampelos-03=http://10.1.0.53:2380
    initial-cluster-state: new
  units:
    - name: etcd2.service
      command: start
    - name: fleet.service
      command: start
